version: "3"
services:
  jenkins:
    image: jenkins/jenkins:latest
    restart: always
    user: root
    ports:
      - "10050:8080"
      - "50000:50000"
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/jianghua/docker/jenkins_home/data:/var/jenkins_home
